=== PythonSanSebastian/pycon-schemas/pycon_schemas/schemas/sponsor.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://pycon.org/sponsor.json",
  "description": "A short schema for Sponsors",
  "title": "Sponsor",
  "type": "object",
  "required": [
    "name",
    "logo"
  ],
  "properties": {
    "name": {
      "description": "Full name of the company",
      "type": "string",
      "examples": [
        "Python Conference"
      ]
    },
    "shortName": {
      "description": "Short name of the company",
      "type": "string",
      "examples": [
        "PyCon"
      ]
    },
    "description": {
      "description": "A description of the company",
      "type": "string",
      "examples": [
        "Super cool company"
      ]
    },
    "url": {
      "description": "The sponsors website",
      "type": "string",
      "examples": [
        "https://www.pycon.org"
      ]
    },
    "logo": {
      "description": "Local path or URL to the logo file",
      "type": "string",
      "examples": [
        "static/pycon_logo.png",
        "https://www.pycon.org/static/logo.png"
      ]
    }
  }
}

=== PythonSanSebastian/pycon-schemas/pycon_schemas/tests/examples/sponsor.json
{
  "name": "Microsoft",
  "shortName": "Microsoft",
  "description": "Microsoft is proud to support the Python Community and the PyCon DE & PyData Berlin Conference. Visual Studio Code, our lightweight, free and open source editor lets developers write better code faster with extensions for Python. Microsoft Azure enables you to develop & run your code easily in the cloud. Azure DevOps supports you to automate the deployment of your data application.",
  "logo": "/static/media/sponsors/microsoft.png"
}
